sudo: false
language: node_js
node_js:
  - "stable"
env:
  global:
    - BUILD_TIMEOUT=10000
install: npm install
after_success: if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run deploy:ci; fi
branches:
  only:
  - master
